### ISSUE TITLE
US1J-13-F as D2

### ISSUE THREAD

**Issue by gashtaan** [newaetech/chipshouter-picoemp#36]
You mentioned diode US1J-13-F as known D2 substitution, but you've never tested it. I'm using it in my build and output seems correct I guess. This is what I measured on the coil:

![picoemp_d2](https://github.com/user-attachments/assets/40b5c592-b135-481b-874f-f2adc86934cc)

**Comment by colinoflynn** [comment]
Thanks for confirming! We had used some in a test build as well, although hadn't finished checking it yet ourselves. We may be swapping to that in our builds so will update the BOM to include this note!
