### ISSUE TITLE
Clarification on BOM Parts

### ISSUE THREAD

**Issue by pk-r7** [newaetech/chipshouter-picoemp#6]
The BOM identifies D2 as a 600V, 2A fast recovery diode. The part # in the BOM and the alternate are both 1A.
C1 and C2 GRM32ER71H475KA88L refers to a 1210 package cap, not an 0805

**Comment by colinoflynn** [comment]
The D2 change is fine (have validated both), I think the 2A was copy-paste error. FWIW the currents (even peak) should be *much* lower as the input primary current is < 1A so the output secondary is going to be mA range. Thanks for fix on C1/C2! Added the PN we use internally for that package (not sure how that happened), it's also in stock at Digikey.

Any preference on BOM file format? I find `.cvs` annoying as it doesn't always import correctly, but the XLS file is hard to view in the repo. I could just use `.cvs` and maybe it's easier for people to catch these.
