### ISSUE TITLE
Battery holder and pin header compatibility

### ISSUE THREAD

**Issue by mehdideveloper** [newaetech/chipshouter-picoemp#9]
Hey
It seems that either J2 or BH1 are the wrong part number here.
I ordered according to BOM (`S2B-XH-A(LF)(SN)` and `PRT-09925`). They do match, but the polarity is reversed. The VCC on battery holder matches the GND on the pin header/PCB.  The one shown in your Youtube video has the right polarity though. 

Please see the attached pictures:

![IMG_2293](https://user-images.githubusercontent.com/12119776/150776779-ddbe1e77-ae28-4856-85f7-5c1cbbd65254.jpg)

![IMG_2292](https://user-images.githubusercontent.com/12119776/150776792-e7bb894a-4bbd-4b94-b8ee-31f5ca97979e.jpg)

Here's yours. Please note the difference:
![maxresdefault](https://user-images.githubusercontent.com/12119776/150776808-2417e818-15c0-4f13-b997-df6ca653f4de.jpeg)

**Comment by BG7YWL** [comment]
![O1CN01ipTIlq2LmDuHIOto2_!!2200547929734](https://user-images.githubusercontent.com/9145406/150778091-af9197e3-72c8-4679-b13c-17731ccfb5fd.jpg)

**Comment by colinoflynn** [comment]
I think yours is defective - see https://www.sparkfun.com/products/9925 which shows the pinout of mine being the same as in the sparkfun photo.

**Comment by mehdideveloper** [comment]
Yes. Digikey is selling the wrong product under Sparkfun PRT-09925. Just reported the error to them.

**Comment by colinoflynn** [comment]
Might have been an error in that batch, as I bought it in December and it was the "right" way around. If you've got a small screwdriver or anything (nail) it's easy to switch the contacts as in that photo.
